services:
  redis:
    image: redis
    networks:
      - frontend
    deploy:
      replicas: 1
    # restart_policy:
    #   condition: on-failure
  
  db:
    image: postgress
    environment:
      POSTGRESS_USER: "postgress"
      POSTGRESS_PASSWORD: "postgress"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.hostname == debian]

  visualiser:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
  backend:

volumes:
  db-data: