services:
  portainer:
    image: portainer/portainer
    deploy:
      placement:
        constraints:
          - node.role == manager  
    ports:
      - "9000:9000" 
    volumes:
      - /data:/data  
      - /var/run/docker.sock:/var/run/docker.sock 
    command: -H unix:///var/run/docker.sock 
